version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-frontend:
    executor:
      name: node/default
    steps:
       - run: echo build-frontend step
  build-backend:
    executor:
      name: node/default
    steps:
       - run: echo build-backend step
  
  test-frontend:
    executor:
      name: node/default
    steps:
      - run: echo test-frontend step
  test-backend:
    executor:
      name: node/default
    steps:
      - run: echo test-backend step

  integration-tests:
    executor:
      name: node/default
    steps:
      - run: echo integration-tests step

  deploy:
    executor:
      name: node/default
    steps:
      - run: echo deploy step
    
workflows:
    build-and-test:
      jobs:
        - build-frontend
        - build-backend
        - test-frontend:
            requires:
              - build-frontend
        - test-backend:
            requires:
              - build-backend
        - integration-tests:
            requires:
              - build-frontend
              - build-backend              
        - deploy:
            requires:
              - test-frontend
              - test-backend
              - integration-tests