version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - run: echo build step $MY_SECRET
      - run: mkdir build_output
      - run: touch build_output/compiled_output.txt
      - persist_to_workspace:
          root: build_output
          paths:
            - '*'

  # build-backend:
  #   executor:
  #     name: node/default
  #   steps:
  #      - run: echo build-backend step
  
  test:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - run: echo test-frontend step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt
          
  # test-backend:
  #   executor:
  #     name: node/default
  #   steps:
  #     - run: echo test-backend step

  # integration-tests:
  #   executor:
  #     name: node/default
  #   steps:
  #     - run: echo integration-tests step

  deploy:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - run: echo deploy step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt
    
workflows:
    build-and-test:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test